import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'vide studio',
    description: 'Generated by create vide himself',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            {children}
        </body>
        </html>
    )
}
