import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import {getPages} from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'vide',
  description: 'Generated by create vide himself',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    // get all pages
    const page = await getPages()
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-3xl mx-auto py-10`}>
      <header className="flex items-center justify-between">
          <Link
              href="/"
              className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
              Vide
          </Link>
          <div>
              {
                  page.map((page) => (
                      <Link
                          key={page._id}
                          href={`/${page.slug}`}
                          className="ml-4 text-gray-500 hover:text-gray-600 hover:underline transition"
                      >
                          {page.title}
                      </Link>
                  ))
              }
          </div>

      </header>
      <main className="py-20">
          {children}
      </main>
      </body>
    </html>
  )
}
